# Generated by Django 4.2.16 on 2026-05-31 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRMEE', 'Confirmée'), ('EN_PREPARATION', 'En préparation'), ('EXPEDIEE', 'Expédiée'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='montant total')),
                ('nom_complet', models.CharField(blank=True, max_length=255, verbose_name='nom complet')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('ville', models.CharField(blank=True, max_length=120, verbose_name='ville')),
                ('code_postal', models.CharField(blank=True, max_length=20, verbose_name='code postal')),
                ('date_commande', models.DateTimeField(auto_now_add=True, verbose_name='date de commande')),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL, verbose_name='client')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'db_table': 'commandes',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=255)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix unitaire')),
                ('quantite', models.PositiveIntegerField(verbose_name='quantité')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='orders.commande')),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_commande', to='products.produit')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
                'db_table': 'lignes_commande',
            },
        ),
    ]
